#basic options
title: This is a TEST
author: Me
email: my.email@gmail.com
description: A wonderful site
twitter_username: no
github_username: no
repository: "Sciencesing/newblog"
logo: "./assests/img/Space_Image_Small"


#Build settings
markdown: kramdown
theme: minima
