#basic options
title: This is a TEST
author: Me
email: my.email@gmail.com
description: A wonderful site
twitter_username: no
github_username: no
repository: "Sciencesing/newblog"
logo: "/assets/img/Space_Image.jpg"

#Build settings
markdown: kramdown
theme: minima
